version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ru.curs:celesta-system-services
    versions:
    - 7.3.33
    - 7.3.35
    - 7.3.38
    - 7.3.39
    - 7.3.40
  - dependency-name: ru.curs:celesta-core
    versions:
    - 7.3.33
    - 7.3.35
    - 7.3.38
    - 7.3.39
    - 7.3.40
  - dependency-name: ru.curs:celesta-parent
    versions:
    - 7.3.33
    - 7.3.35
    - 7.3.38
    - 7.3.39
    - 7.3.40
